import logging
from typing import List, Dict, Optional
from domain.entities.schema_metadata import (
    TableClassification,
    ColumnMetadata,
    DbtModelSpec,
    FlexfieldInfo,
)

logger = logging.getLogger(__name__)

# Oracle-to-BigQuery type mapping
ORACLE_TO_BQ_TYPE_MAP: Dict[str, str] = {
    "VARCHAR2": "STRING",
    "NVARCHAR2": "STRING",
    "CHAR": "STRING",
    "NCHAR": "STRING",
    "CLOB": "STRING",
    "NCLOB": "STRING",
    "NUMBER": "NUMERIC",
    "FLOAT": "FLOAT64",
    "BINARY_FLOAT": "FLOAT64",
    "BINARY_DOUBLE": "FLOAT64",
    "DATE": "TIMESTAMP",
    "TIMESTAMP": "TIMESTAMP",
    "RAW": "BYTES",
    "BLOB": "BYTES",
    "LONG": "STRING",
    "XMLTYPE": "STRING",
    "ROWID": "STRING",
}


class CodeGeneratorService:
    """Domain service that generates dbt model SQL and YAML from Oracle table metadata.

    Transforms Oracle SIE classifications into dbt-compatible models following
    the medallion architecture (staging -> intermediate -> mart).
    """

    def map_oracle_type_to_bq(self, oracle_type: str) -> str:
        """Map an Oracle data type to a BigQuery-compatible type."""
        base_type = oracle_type.split("(")[0].upper().strip()
        return ORACLE_TO_BQ_TYPE_MAP.get(base_type, "STRING")

    def generate_model_name(self, table_name: str, layer: str) -> str:
        """Generate a dbt model name from the Oracle table name and layer."""
        clean_name = table_name.lower().replace("_all", "").rstrip("_")
        prefix_map = {"staging": "stg", "intermediate": "int", "mart": "mart"}
        prefix = prefix_map.get(layer, layer)
        return f"{prefix}_{clean_name}"

    def generate_staging_sql(self, table: TableClassification) -> str:
        """Generate the SQL for a dbt staging model."""
        source_ref = f"{{{{ source('oracle_{table.module.lower()}', '{table.table_name.lower()}') }}}}"
        column_casts = []
        for col in table.columns:
            bq_type = self.map_oracle_type_to_bq(col.data_type)
            alias = col.column_name.lower()
            column_casts.append(f"    CAST({col.column_name} AS {bq_type}) AS {alias}")

        columns_sql = ",\n".join(column_casts) if column_casts else "    *"

        sql = f"""-- Generated by OracleForge Code Generator
-- Source: {table.table_name} (Module: {table.module})

WITH source AS (
    SELECT * FROM {source_ref}
),

renamed AS (
    SELECT
{columns_sql}
    FROM source
)

SELECT * FROM renamed
"""
        return sql

    def generate_staging_yaml(self, table: TableClassification, model_name: str) -> str:
        """Generate the YAML schema file for a dbt staging model."""
        description = table.description or f"Staging model for Oracle {table.table_name}"
        lines = [
            "version: 2",
            "",
            "models:",
            f"  - name: {model_name}",
            f"    description: \"{description}\"",
            f"    config:",
            f"      materialized: view",
            f"      tags: ['{table.module.lower()}', 'staging', 'oracle_migration']",
            f"    columns:",
        ]

        for col in table.columns:
            col_desc = ""
            if col.is_primary_key:
                col_desc = "Primary key. "
            if col.is_foreign_key and col.fk_target_table:
                col_desc += f"Foreign key to {col.fk_target_table}.{col.fk_target_column}. "
            lines.append(f"      - name: {col.column_name.lower()}")
            if col_desc:
                lines.append(f"        description: \"{col_desc.strip()}\"")
            if col.is_primary_key:
                lines.append(f"        tests:")
                lines.append(f"          - unique")
                lines.append(f"          - not_null")

        # Add flexfield documentation
        if table.has_flexfields:
            lines.append("")
            lines.append(f"    meta:")
            lines.append(f"      flexfields:")
            for ff in table.flexfields:
                lines.append(f"        - type: {ff.flexfield_type}")
                if ff.structure_name:
                    lines.append(f"          structure: \"{ff.structure_name}\"")
                lines.append(f"          columns: [{', '.join(ff.columns)}]")

        return "\n".join(lines) + "\n"

    def generate_intermediate_sql(self, table: TableClassification) -> str:
        """Generate SQL for an intermediate dbt model with business transformations."""
        stg_model = self.generate_model_name(table.table_name, "staging")
        stg_ref = f"{{{{ ref('{stg_model}') }}}}"

        # Build column list
        columns = [f"    {col.column_name.lower()}" for col in table.columns]

        # Add flexfield unpacking for segments
        extra_cols = []
        if table.segment_columns:
            extra_cols.append("")
            extra_cols.append("    -- Flexfield segments (unpacked)")
            for seg in table.segment_columns:
                extra_cols.append(f"    {seg.lower()} AS {seg.lower()}_value")

        columns_sql = ",\n".join(columns)

        sql = f"""-- Generated by OracleForge Code Generator
-- Intermediate model for {table.table_name}

WITH staged AS (
    SELECT * FROM {stg_ref}
),

transformed AS (
    SELECT
{columns_sql}
    FROM staged
)

SELECT * FROM transformed
"""
        return sql

    def generate_source_yaml(self, tables: List[TableClassification], module: str) -> str:
        """Generate a dbt sources YAML file for a group of Oracle tables."""
        lines = [
            "version: 2",
            "",
            "sources:",
            f"  - name: oracle_{module.lower()}",
            f"    description: \"Oracle EBS {module} module tables migrated to BigQuery\"",
            f"    database: \"{{{{ var('bq_project') }}}}\"",
            f"    schema: \"bronze_{module.lower()}\"",
            f"    tables:",
        ]
        for table in tables:
            lines.append(f"      - name: {table.table_name.lower()}")
            if table.description:
                lines.append(f"        description: \"{table.description}\"")
            if table.estimated_row_count:
                lines.append(f"        meta:")
                lines.append(f"          estimated_rows: {table.estimated_row_count}")

        return "\n".join(lines) + "\n"

    def build_staging_model(self, table: TableClassification) -> DbtModelSpec:
        """Build a complete staging DbtModelSpec from a classified table."""
        model_name = self.generate_model_name(table.table_name, "staging")
        sql = self.generate_staging_sql(table)
        yaml = self.generate_staging_yaml(table, model_name)

        return DbtModelSpec(
            model_name=model_name,
            source_table=table.table_name,
            module=table.module,
            layer="staging",
            sql_content=sql,
            yaml_content=yaml,
            description=f"Staging model for Oracle {table.table_name}",
            materialization="view",
            tags=[table.module.lower(), "staging", "oracle_migration"],
        )

    def build_intermediate_model(self, table: TableClassification) -> DbtModelSpec:
        """Build a complete intermediate DbtModelSpec from a classified table."""
        model_name = self.generate_model_name(table.table_name, "intermediate")
        sql = self.generate_intermediate_sql(table)
        yaml = self.generate_staging_yaml(table, model_name)  # reuse schema structure

        return DbtModelSpec(
            model_name=model_name,
            source_table=table.table_name,
            module=table.module,
            layer="intermediate",
            sql_content=sql,
            yaml_content=yaml,
            description=f"Intermediate model for Oracle {table.table_name}",
            materialization="view",
            tags=[table.module.lower(), "intermediate", "oracle_migration"],
        )
