import logging
import os
from typing import List
from domain.entities.schema_metadata import TableClassification, DbtModelSpec
from domain.ports.code_generator_ports import CodeGeneratorPort
from domain.services.code_generator_service import CodeGeneratorService

logger = logging.getLogger(__name__)


class DbtGeneratorAdapter(CodeGeneratorPort):
    """Adapter that generates and writes dbt model files to disk."""

    def __init__(self, output_base_dir: str = "dbt_project"):
        self.output_base_dir = output_base_dir
        self.service = CodeGeneratorService()

    async def generate_staging_model(self, table: TableClassification) -> DbtModelSpec:
        """Generate a dbt staging model using the domain service."""
        logger.info(f"Generating staging model for {table.table_name}")
        return self.service.build_staging_model(table)

    async def generate_intermediate_model(self, table: TableClassification) -> DbtModelSpec:
        """Generate a dbt intermediate model using the domain service."""
        logger.info(f"Generating intermediate model for {table.table_name}")
        return self.service.build_intermediate_model(table)

    async def generate_mart_model(self, tables: List[TableClassification]) -> DbtModelSpec:
        """Generate a dbt mart model joining related tables."""
        logger.info(f"Generating mart model for {len(tables)} tables")
        # Simplified: generate a mart that unions/joins the staging models
        table_refs = []
        all_tags = set()
        for t in tables:
            stg_name = self.service.generate_model_name(t.table_name, "staging")
            table_refs.append(f"SELECT * FROM {{{{ ref('{stg_name}') }}}}")
            all_tags.add(t.module.lower())

        module = tables[0].module if tables else "UNKNOWN"
        model_name = f"mart_{module.lower()}_combined"

        sql = f"-- Generated by OracleForge Code Generator\n-- Mart model\n\n"
        sql += "\nUNION ALL\n".join(table_refs)

        yaml = (
            f"version: 2\n\nmodels:\n  - name: {model_name}\n"
            f"    description: \"Mart model combining {module} tables\"\n"
            f"    config:\n      materialized: table\n"
            f"      tags: ['{module.lower()}', 'mart', 'oracle_migration']\n"
        )

        return DbtModelSpec(
            model_name=model_name,
            source_table=", ".join(t.table_name for t in tables),
            module=module,
            layer="mart",
            sql_content=sql,
            yaml_content=yaml,
            description=f"Mart model combining {module} tables",
            materialization="table",
            tags=list(all_tags) + ["mart", "oracle_migration"],
        )

    async def write_model_files(self, model: DbtModelSpec, output_dir: str) -> List[str]:
        """Write generated SQL and YAML files to the filesystem."""
        layer_dir = os.path.join(output_dir or self.output_base_dir, "models", model.layer)
        os.makedirs(layer_dir, exist_ok=True)

        sql_path = os.path.join(layer_dir, f"{model.model_name}.sql")
        yaml_path = os.path.join(layer_dir, f"{model.model_name}.yml")

        written_files = []

        with open(sql_path, "w") as f:
            f.write(model.sql_content)
        written_files.append(sql_path)
        logger.info(f"Wrote SQL model: {sql_path}")

        with open(yaml_path, "w") as f:
            f.write(model.yaml_content)
        written_files.append(yaml_path)
        logger.info(f"Wrote YAML schema: {yaml_path}")

        return written_files
